# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.11

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/carels/astro-accelerate

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/carels/astro-accelerate

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/carels/astro-accelerate/CMakeFiles /home/carels/astro-accelerate/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/carels/astro-accelerate/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named astro-accelerate

# Build rule for target.
astro-accelerate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 astro-accelerate
.PHONY : astro-accelerate

# fast build rule for target.
astro-accelerate/fast:
	$(MAKE) -f CMakeFiles/astro-accelerate.dir/build.make CMakeFiles/astro-accelerate.dir/build
.PHONY : astro-accelerate/fast

#=============================================================================
# Target rules for targets named astroaccelerate

# Build rule for target.
astroaccelerate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 astroaccelerate
.PHONY : astroaccelerate

# fast build rule for target.
astroaccelerate/fast:
	$(MAKE) -f CMakeFiles/astroaccelerate.dir/build.make CMakeFiles/astroaccelerate.dir/build
.PHONY : astroaccelerate/fast

src/characteristics.o: src/characteristics.cpp.o

.PHONY : src/characteristics.o

# target to build an object file
src/characteristics.cpp.o:
	$(MAKE) -f CMakeFiles/astro-accelerate.dir/build.make CMakeFiles/astro-accelerate.dir/src/characteristics.cpp.o
.PHONY : src/characteristics.cpp.o

src/characteristics.i: src/characteristics.cpp.i

.PHONY : src/characteristics.i

# target to preprocess a source file
src/characteristics.cpp.i:
	$(MAKE) -f CMakeFiles/astro-accelerate.dir/build.make CMakeFiles/astro-accelerate.dir/src/characteristics.cpp.i
.PHONY : src/characteristics.cpp.i

src/characteristics.s: src/characteristics.cpp.s

.PHONY : src/characteristics.s

# target to generate assembly for a file
src/characteristics.cpp.s:
	$(MAKE) -f CMakeFiles/astro-accelerate.dir/build.make CMakeFiles/astro-accelerate.dir/src/characteristics.cpp.s
.PHONY : src/characteristics.cpp.s

src/dcdflib.o: src/dcdflib.cpp.o

.PHONY : src/dcdflib.o

# target to build an object file
src/dcdflib.cpp.o:
	$(MAKE) -f CMakeFiles/astro-accelerate.dir/build.make CMakeFiles/astro-accelerate.dir/src/dcdflib.cpp.o
.PHONY : src/dcdflib.cpp.o

src/dcdflib.i: src/dcdflib.cpp.i

.PHONY : src/dcdflib.i

# target to preprocess a source file
src/dcdflib.cpp.i:
	$(MAKE) -f CMakeFiles/astro-accelerate.dir/build.make CMakeFiles/astro-accelerate.dir/src/dcdflib.cpp.i
.PHONY : src/dcdflib.cpp.i

src/dcdflib.s: src/dcdflib.cpp.s

.PHONY : src/dcdflib.s

# target to generate assembly for a file
src/dcdflib.cpp.s:
	$(MAKE) -f CMakeFiles/astro-accelerate.dir/build.make CMakeFiles/astro-accelerate.dir/src/dcdflib.cpp.s
.PHONY : src/dcdflib.cpp.s

src/fresnl.o: src/fresnl.cpp.o

.PHONY : src/fresnl.o

# target to build an object file
src/fresnl.cpp.o:
	$(MAKE) -f CMakeFiles/astro-accelerate.dir/build.make CMakeFiles/astro-accelerate.dir/src/fresnl.cpp.o
.PHONY : src/fresnl.cpp.o

src/fresnl.i: src/fresnl.cpp.i

.PHONY : src/fresnl.i

# target to preprocess a source file
src/fresnl.cpp.i:
	$(MAKE) -f CMakeFiles/astro-accelerate.dir/build.make CMakeFiles/astro-accelerate.dir/src/fresnl.cpp.i
.PHONY : src/fresnl.cpp.i

src/fresnl.s: src/fresnl.cpp.s

.PHONY : src/fresnl.s

# target to generate assembly for a file
src/fresnl.cpp.s:
	$(MAKE) -f CMakeFiles/astro-accelerate.dir/build.make CMakeFiles/astro-accelerate.dir/src/fresnl.cpp.s
.PHONY : src/fresnl.cpp.s

src/ipmpar.o: src/ipmpar.cpp.o

.PHONY : src/ipmpar.o

# target to build an object file
src/ipmpar.cpp.o:
	$(MAKE) -f CMakeFiles/astro-accelerate.dir/build.make CMakeFiles/astro-accelerate.dir/src/ipmpar.cpp.o
.PHONY : src/ipmpar.cpp.o

src/ipmpar.i: src/ipmpar.cpp.i

.PHONY : src/ipmpar.i

# target to preprocess a source file
src/ipmpar.cpp.i:
	$(MAKE) -f CMakeFiles/astro-accelerate.dir/build.make CMakeFiles/astro-accelerate.dir/src/ipmpar.cpp.i
.PHONY : src/ipmpar.cpp.i

src/ipmpar.s: src/ipmpar.cpp.s

.PHONY : src/ipmpar.s

# target to generate assembly for a file
src/ipmpar.cpp.s:
	$(MAKE) -f CMakeFiles/astro-accelerate.dir/build.make CMakeFiles/astro-accelerate.dir/src/ipmpar.cpp.s
.PHONY : src/ipmpar.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/astro-accelerate.dir/build.make CMakeFiles/astro-accelerate.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/astro-accelerate.dir/build.make CMakeFiles/astro-accelerate.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/astro-accelerate.dir/build.make CMakeFiles/astro-accelerate.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/median.o: src/median.cpp.o

.PHONY : src/median.o

# target to build an object file
src/median.cpp.o:
	$(MAKE) -f CMakeFiles/astro-accelerate.dir/build.make CMakeFiles/astro-accelerate.dir/src/median.cpp.o
.PHONY : src/median.cpp.o

src/median.i: src/median.cpp.i

.PHONY : src/median.i

# target to preprocess a source file
src/median.cpp.i:
	$(MAKE) -f CMakeFiles/astro-accelerate.dir/build.make CMakeFiles/astro-accelerate.dir/src/median.cpp.i
.PHONY : src/median.cpp.i

src/median.s: src/median.cpp.s

.PHONY : src/median.s

# target to generate assembly for a file
src/median.cpp.s:
	$(MAKE) -f CMakeFiles/astro-accelerate.dir/build.make CMakeFiles/astro-accelerate.dir/src/median.cpp.s
.PHONY : src/median.cpp.s

src/presto_funcs.o: src/presto_funcs.cpp.o

.PHONY : src/presto_funcs.o

# target to build an object file
src/presto_funcs.cpp.o:
	$(MAKE) -f CMakeFiles/astro-accelerate.dir/build.make CMakeFiles/astro-accelerate.dir/src/presto_funcs.cpp.o
.PHONY : src/presto_funcs.cpp.o

src/presto_funcs.i: src/presto_funcs.cpp.i

.PHONY : src/presto_funcs.i

# target to preprocess a source file
src/presto_funcs.cpp.i:
	$(MAKE) -f CMakeFiles/astro-accelerate.dir/build.make CMakeFiles/astro-accelerate.dir/src/presto_funcs.cpp.i
.PHONY : src/presto_funcs.cpp.i

src/presto_funcs.s: src/presto_funcs.cpp.s

.PHONY : src/presto_funcs.s

# target to generate assembly for a file
src/presto_funcs.cpp.s:
	$(MAKE) -f CMakeFiles/astro-accelerate.dir/build.make CMakeFiles/astro-accelerate.dir/src/presto_funcs.cpp.s
.PHONY : src/presto_funcs.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... astro-accelerate"
	@echo "... astroaccelerate"
	@echo "... src/characteristics.o"
	@echo "... src/characteristics.i"
	@echo "... src/characteristics.s"
	@echo "... src/dcdflib.o"
	@echo "... src/dcdflib.i"
	@echo "... src/dcdflib.s"
	@echo "... src/fresnl.o"
	@echo "... src/fresnl.i"
	@echo "... src/fresnl.s"
	@echo "... src/ipmpar.o"
	@echo "... src/ipmpar.i"
	@echo "... src/ipmpar.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/median.o"
	@echo "... src/median.i"
	@echo "... src/median.s"
	@echo "... src/presto_funcs.o"
	@echo "... src/presto_funcs.i"
	@echo "... src/presto_funcs.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

