set(lib_src_cuda
    host_acceleration.cu
    host_write_file.cu  
    device_main.cu
    host_allocate_memory.cu
    host_analysis.cu
    host_periods.cu
    host_debug.cu
    host_get_file_data.cu
    host_get_user_input.cu
    host_get_recorded_data.cu
    host_help.cu
    host_rfi.cu
    host_stratagy.cu  
    host_statistics.cu
    host_main_function.h
    fresnl.c
    median.c    
    presto_funcs.c  
    characteristics.c
    dcdflib.c 
    ipmpar.c
    fdas_host.cu
    fdas_device.cu
    fdas_util.cu
)
