#define SNUMREG 12
#define SDIVINT 10
#define SDIVINDM 72
#define SFDIVINDM 72.0f
#define CARD 0
#define NOPSSHIFT 5
#define NOPSLOOP 3
#define NDATAPERLOOP 1
#define BINDIVINT 6
#define BINDIVINF 32
#define CT 256
#define CF 2
#define NOPS 4.0
